version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openlab
      TZ: 'Asia/Tokyo'
    volumes:
      - ./MySQL/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./MySQL:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
  sqler:
    image: alash3al/sqler
    restart: always
    entrypoint:
      - sqler
      - -dsn=root:root@tcp(mysql:3306)/openlab
      - -config=/root/config.hcl
    volumes:
      - ./SQLer/config.hcl:/root/config.hcl
    ports:
      - 8025:8025